
server:
  port: 8003

spring:
  redis:
    database: 0
    host: 127.0.0.1:6379
    port: 6379
#开启Mybatis日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

website:
  domain-name:mediafound.com
